version: '3.9'


services:
  app:
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
    working_dir: /wd
    ports:
      - "5000:5000"
    command:
      - --host=0.0.0.0